### ISSUE TITLE
"Invoked program with no predicate named main" error occurs in unrelated syntax error cases

### ISSUE THREAD

**Issue by kwalberg** [jacobdweightman/allium#2]
The "Invoked program with no predicate named main" error gets thrown in cases where main is defined but some other syntax error is present. There are a lot of cases where this happens, but from what I can tell all of the cases boil down to any unexpected text appearing outside of a pair of curly braces.

**Comment by jacobdweightman** [comment]
Thanks for all of your work on this! Sorry about the scope creep, I'll try not to do that again 🙇‍♂️
