### ISSUE TITLE
allium-ls functional tests hang on Windows

### ISSUE THREAD

**Issue by jacobdweightman** [jacobdweightman/allium#8]
The Allium Language Server functional tests hang on Windows. This might be caused by building with MSVC++ or running on the Windows operating system; I'm not sure, and since I don't have a Windows PC all I have to go on is the limited information available from the [GitHub CI pipeline](https://github.com/jacobdweightman/allium/runs/3571886502?check_suite_focus=true).

This test is disabled for MSVC, and the language server likely will not work on Windows until this is resolved.
```
if(NOT MSVC)
add_test(NAME language-server-functional-tests
  COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/tests/languageserver.py $<TARGET_FILE:allium-ls>)
endif()
```

**Comment by kwalberg** [comment]
Some time here soon I'm planning on setting up the build dependencies on Windows so that I can test this. I can also try to debug the intermittent build failures we've been getting in the GitHub pipeline.

**Comment by kwalberg** [comment]
Got my dev environment set up. It looks like both categories of functional tests are failing due to the "The system cannot find the file specified" error that we've been seeing. There might be a separate issue with the allium-ls functional tests that is being obscured by that issue.

**Comment by jacobdweightman** [comment]
Just to document our recent conversation, it seems likely that there is a conflict between the Cmake target for the Allium interpreter executable and the runtime library used by compiled Allium programs — one is called `allium`, and the other is called `Allium`. This might be Windows-specific because file names are case-sensitive on Windows, but case-insensitive on Mac OS and Linux.

This intermittent pipeline failure is newer than this issue — if the diagnosis above is correct, then it was introduced by [this commit](https://github.com/jacobdweightman/allium/runs/5766448908?check_suite_focus=true). The issue reported here is a distinct, older issue. It might be an issue with the test harness, or it might be an issue with the language server itself. My initial development of the language server was done on Mac OS, so I never tested it directly on Windows outside the CI pipeline (which made it hard to debug).

Once this is fixed, we'll be in a position to build out the language server and start on a VS Code (or other editor) plugin.

**Comment by jacobdweightman** [comment]
I thought it would be best to fix the CI issue ASAP, so I went ahead and did that already. Hopefully it's smooth sailing from here.
https://github.com/jacobdweightman/allium/runs/6517746742?check_suite_focus=true
